// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebApp.Models;

#nullable disable

namespace WebApp.Migrations
{
    [DbContext(typeof(PostgresContext))]
    [Migration("20250129125954_AddTestMigrationColumn")]
    partial class AddTestMigrationColumn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "appointmenttypeenum", new[] { "GP", "KRV", "X-RAY", "CT", "MR", "ULTRA", "EKG", "ECHO", "EYE", "DERM", "DENTA", "MAMMO", "NEURO" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "auth", "aal_level", new[] { "aal1", "aal2", "aal3" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "auth", "code_challenge_method", new[] { "s256", "plain" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "auth", "factor_status", new[] { "unverified", "verified" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "auth", "factor_type", new[] { "totp", "webauthn", "phone" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "auth", "one_time_token_type", new[] { "confirmation_token", "reauthentication_token", "recovery_token", "email_change_token_new", "email_change_token_current", "phone_change_token" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "pgsodium", "key_status", new[] { "default", "valid", "invalid", "expired" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "pgsodium", "key_type", new[] { "aead-ietf", "aead-det", "hmacsha512", "hmacsha256", "auth", "shorthash", "generichash", "kdf", "secretbox", "secretstream", "stream_xchacha20" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "realtime", "action", new[] { "INSERT", "UPDATE", "DELETE", "TRUNCATE", "ERROR" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "realtime", "equality_op", new[] { "eq", "neq", "lt", "lte", "gt", "gte", "in" });
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "extensions", "pg_stat_statements");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "extensions", "pgcrypto");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "extensions", "pgjwt");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "extensions", "uuid-ossp");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "graphql", "pg_graphql");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pgsodium", "pgsodium");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vault", "supabase_vault");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence<int>("seq_schema_version", "graphql")
                .IsCyclic();

            modelBuilder.Entity("WebApp.Models.Appointment", b =>
                {
                    b.Property<int>("Appointmentid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("appointmentid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Appointmentid"));

                    b.Property<DateTime>("Appointmentdate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("appointmentdate");

                    b.Property<int>("Appointmenttypeid")
                        .HasColumnType("integer")
                        .HasColumnName("appointmenttypeid");

                    b.Property<int>("Patientid")
                        .HasColumnType("integer")
                        .HasColumnName("patientid");

                    b.HasKey("Appointmentid")
                        .HasName("appointments_pkey");

                    b.HasIndex("Appointmenttypeid");

                    b.HasIndex("Patientid");

                    b.ToTable("appointments", (string)null);
                });

            modelBuilder.Entity("WebApp.Models.Appointmenttype", b =>
                {
                    b.Property<int>("Appointmenttypeid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("appointmenttypeid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Appointmenttypeid"));

                    b.Property<string>("Appointmenttypename")
                        .HasColumnType("text")
                        .HasColumnName("appointmenttypename");

                    b.HasKey("Appointmenttypeid")
                        .HasName("appointmenttypes_pkey");

                    b.ToTable("appointmenttypes", (string)null);
                });

            modelBuilder.Entity("WebApp.Models.Attachment", b =>
                {
                    b.Property<int>("Attachmentid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("attachmentid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Attachmentid"));

                    b.Property<int>("Appointmentid")
                        .HasColumnType("integer")
                        .HasColumnName("appointmentid");

                    b.Property<string>("Filename")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("filename");

                    b.Property<string>("Filepath")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("filepath");

                    b.Property<DateTime?>("Uploadedat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("uploadedat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Attachmentid")
                        .HasName("attachments_pkey");

                    b.HasIndex("Appointmentid");

                    b.ToTable("attachments", (string)null);
                });

            modelBuilder.Entity("WebApp.Models.Medicalrecord", b =>
                {
                    b.Property<int>("Recordid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("recordid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Recordid"));

                    b.Property<string>("Diseasename")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("diseasename");

                    b.Property<DateOnly?>("Enddate")
                        .HasColumnType("date")
                        .HasColumnName("enddate");

                    b.Property<int>("Patientid")
                        .HasColumnType("integer")
                        .HasColumnName("patientid");

                    b.Property<DateOnly>("Startdate")
                        .HasColumnType("date")
                        .HasColumnName("startdate");

                    b.HasKey("Recordid")
                        .HasName("medicalrecords_pkey");

                    b.HasIndex("Patientid");

                    b.ToTable("medicalrecords", (string)null);
                });

            modelBuilder.Entity("WebApp.Models.Patient", b =>
                {
                    b.Property<int>("Patientid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("patientid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Patientid"));

                    b.Property<DateTime>("Dateofbirth")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dateofbirth");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("firstname");

                    b.Property<char>("Gender")
                        .HasMaxLength(1)
                        .HasColumnType("character(1)")
                        .HasColumnName("gender");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("lastname");

                    b.Property<string>("Oib")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("oib");

                    b.Property<string>("TestMigrationColumn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Patientid")
                        .HasName("patients_pkey");

                    b.HasIndex(new[] { "Oib" }, "patients_oib_key")
                        .IsUnique();

                    b.ToTable("patients", (string)null);
                });

            modelBuilder.Entity("WebApp.Models.Prescription", b =>
                {
                    b.Property<int>("Prescriptionid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("prescriptionid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Prescriptionid"));

                    b.Property<string>("Medicinename")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("medicinename");

                    b.Property<int>("Patientid")
                        .HasColumnType("integer")
                        .HasColumnName("patientid");

                    b.HasKey("Prescriptionid")
                        .HasName("prescriptions_pkey");

                    b.HasIndex("Patientid");

                    b.ToTable("prescriptions", (string)null);
                });

            modelBuilder.Entity("WebApp.Models.Appointment", b =>
                {
                    b.HasOne("WebApp.Models.Appointmenttype", "Appointmenttype")
                        .WithMany("Appointments")
                        .HasForeignKey("Appointmenttypeid")
                        .IsRequired()
                        .HasConstraintName("appointments_appointmenttypeid_fkey");

                    b.HasOne("WebApp.Models.Patient", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("Patientid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("appointments_patientid_fkey");

                    b.Navigation("Appointmenttype");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("WebApp.Models.Attachment", b =>
                {
                    b.HasOne("WebApp.Models.Appointment", "Appointment")
                        .WithMany("Attachments")
                        .HasForeignKey("Appointmentid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("attachments_appointmentid_fkey");

                    b.Navigation("Appointment");
                });

            modelBuilder.Entity("WebApp.Models.Medicalrecord", b =>
                {
                    b.HasOne("WebApp.Models.Patient", "Patient")
                        .WithMany("Medicalrecords")
                        .HasForeignKey("Patientid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("medicalrecords_patientid_fkey");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("WebApp.Models.Prescription", b =>
                {
                    b.HasOne("WebApp.Models.Patient", "Patient")
                        .WithMany("Prescriptions")
                        .HasForeignKey("Patientid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("prescriptions_patientid_fkey");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("WebApp.Models.Appointment", b =>
                {
                    b.Navigation("Attachments");
                });

            modelBuilder.Entity("WebApp.Models.Appointmenttype", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("WebApp.Models.Patient", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Medicalrecords");

                    b.Navigation("Prescriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
